[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Credit to NotJustYet for this scrumptious section of code! Mod priority is 2 because NotJustYet needs to go first.
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if G.GAME.chips - G.GAME.blind.chips >= 0 or G.GAME.current_round.hands_left < 1 then"
position = "at"
payload = '''
if (G.GAME.chips - G.GAME.blind.chips >= 0 and not next(SMODS.find_card("j_bfdi_loser"))) or G.GAME.current_round.hands_left < 1 then
	stop_use()
'''
match_indent = true

# Talisman
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if Big:new(G.GAME.chips) >= Big:new(G.GAME.blind.chips) or G.GAME.current_round.hands_left < 1 then"
position = "at"
payload = '''
if (Big:new(G.GAME.chips) >= Big:new(G.GAME.blind.chips) and not next(SMODS.find_card("j_bfdi_loser"))) or G.GAME.current_round.hands_left < 1 then
	stop_use()
'''
match_indent = true

# LobCorp
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if to_big(G.GAME.chips) >= to_big(G.GAME.blind.chips) or G.GAME.current_round.hands_left <= 0 then"
position = "at"
payload = '''
if (to_big(G.GAME.chips) >= to_big(G.GAME.blind.chips) and not next(SMODS.find_card("j_bfdi_loser"))) or G.GAME.current_round.hands_left <= 0 then
	stop_use()
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if #G.hand.cards < 1 and #G.deck.cards < 1 and #G.play.cards < 1 then"
position = "at"
payload = '''
if not true then
'''
match_indent = true